language: python
python:
- '3.6'
env:
- TOKEN=12345678
services:
- docker
install:
- make dep
before_script:
- make db-up
- sleep 180
- make services-up
script:
- python end_to_end_test.py
- make db-down
notifications:
  slack:
    secure: WTmwjo3O720Dzbey3y9hcqAxFrGpOl01m8KMBqMejZ8NPlfGCDH5GJJ5UAsSN4I9uC+oeyYrsVnwf6kZKMVwFElC7733aNdrP5+YxPp0CwEKRh68YZO+t6T3PjMB/u/RWADlWnbhniRse+GAEa0E1pGIRhwiyVVG7sxrDY1kpyZy8jXZ1VxRVVz/akcd3CtgpJ+Qx2W3eEVREPu8HTEISStt5oG7kbRQ+AingTc164nI4bdlQgKJK13LwqrvrcOwPccuEuWFOgdMyyQyNdrIUalIxDi0tGZtr5SMam9RFnNiY/fgbJomCyrOJj5NnmNqvtF8y9k1lVlpznEuQMSVDliuG7yff4zyV8K7EdH3jWXjfblLONgAvHj6zd+8R4sSywZZAf7TdijB9t3KC/YIheqSTxAe17fGT3Gs2y6b0Jvxljph9GXyBmMQpisOk5t9kpM61ERhFNiTEANt7shXP/g+WPFb6knXc4pJMwTLGhL9TYWFhaG6Vy1JJwQ0Anum9NCmJnxkh0+2Lavh51MXQOCzE9jP4oBWO7XGwil30YlATdR/bZtwAgy9hUW11ZZ61uUa2IcvAHLWJAJo5uq886iLnUlMlTXcF54LRwQoTGLE1rewZVhlpPM0HwkH5/09UA6S6MyW2GAapMckK/3oPa3Y4A1bHbNvG6+rWDHJvoo=
